---
title: "NOTES"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Steps for cleaning
## Load the CSV files

### FILE:
In general terms:
THINK: missing values ( 300 plus NAs if merging with PAM50)

1) Load
2) Find the duplicates
3) Remove the duplicates
4) Replicates of normal samples

#### Clinical data:
When joining the extra values will be dropped
Change the ID's
Change the col names wo spaces
Order of cols: with ID column first for convenience

#### Proteome data:
Removing the normal patients
Find the duplicates : patients: combine the samples into one
                       
#### PAM50 data: 


QUESTIONS for Leon:
Data format: wide, long
Combine clinical and proteome data: should we use that in tandem for modeeling, or two separate analyses 


Thigs to maybe do:
PCA maybe ?
Heatmap for genes/tumor types vs top expressed top/down genes ?
Log2 distribution ??? but for 77 samples might eb too much or maybe it overlaps well
Venn diagram ??? 
Enrichment analysis ( some packages are available: "ClusterProfile" )
Check The paper for ideas
Check the kernel for ideas